version: '3'

services:
  app:
    image: node:latest
    restart: 'no'
    volumes:
      - ${PWD}./:/usr/src/app
    ports:
      - 80:3000
    command: ["bash", "/usr/src/app/command.sh"]
  mongo:
    image: mongo
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1
  mongo-express:
    image: mongo-express
    restart: 'no'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example1
    links:
      - mongo
    depends_on:
      - mongo
